### ISSUE TITLE
Issue with pinnedrepos

### ISSUE THREAD

**Issue by Zinedinarnaut** [chenelias/eliaschen.dev#1]
Got a quick question, why doesn't the pinnedrepos show up anymore?

**Comment by chenelias** [comment]
There is some issue going on in egoist/gh-pinned-repos(the api I use for pinnedrepos).

**Comment by chenelias** [comment]
Also I'm kind of busy right now, so I just hide that section without fixing it.

**Comment by Zinedinarnaut** [comment]
Found a temp fix for it https://github.com/egoist/gh-pinned-repos/issues/22

**Comment by chenelias** [comment]
Thanks, fixed in 290df13
